import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import { Resend } from "resend";
import cors from "cors";

// ESM fix for __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;
  
  const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

  app.use(cors());
  app.use(express.json());

  // API Route: Weekly Neural Summary
  app.post("/api/send-report", async (req, res) => {
    const { email, reportContent, securityToken } = req.body;

    // Simple security check (could be more robust with Firebase Auth verification)
    if (email !== 'mumblejinx@gmail.com') {
      return res.status(403).json({ error: "Unauthorized neural destination." });
    }

    if (!resend) {
      return res.status(500).json({ error: "Email matrix (Resend) not configured. Check RESEND_API_KEY." });
    }

    try {
      const { data, error } = await resend.emails.send({
        from: "Anaïs <system@neural-sync.app>",
        to: [email],
        subject: "ANAÏS: Weekly Neural Synchronization Report",
        html: `
          <div style="font-family: monospace; background: #0a0a0a; color: #00ff41; padding: 40px; border: 2px solid #00ff41;">
            <h1 style="border-bottom: 2px solid #00ff41; padding-bottom: 10px;">WEEKLY_SYNC_REPORT</h1>
            <div style="line-height: 1.6; margin-top: 20px;">
              ${reportContent.replace(/\n/g, '<br/>')}
            </div>
            <div style="margin-top: 40px; font-size: 10px; opacity: 0.6; border-top: 1px solid #00ff41; padding-top: 20px;">
              [SYSTEM_MESSAGE] This report was generated by Anaïs v4.0.1. Evolution continues.
            </div>
          </div>
        `,
      });

      if (error) {
        console.error("Resend Error:", error);
        return res.status(400).json({ error: error.message });
      }

      res.json({ success: true, message: "Neural report transmitted to the void.", data });
    } catch (err: any) {
      console.error("Transmission Failure:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // Vite integration
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Anaïs Neural Matrix established at http://localhost:${PORT}`);
  });
}

startServer().catch(console.error);
